version: '3.8'

services:
  # --- 1. (PostgreSQL) ---
  db:
    image: postgres:16-alpine
    container_name: albion_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # We open the port to the outside so that you can connect via DBeaver/PyCharm.
    volumes:
      - ./pg_data:/var/lib/postgresql/data # We save data to disk so that it does not disappear when restarting.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. GUI for db (Adminer) ---
  adminer:
    image: adminer
    container_name: albion_adminer
    restart: always
    ports:
      - "8080:8080" # http://localhost:8080
    depends_on:
      - db

  # --- 3. Backend API ---
  api:
    build: .
    container_name: albion_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src # "Hot Reload": change the code locally â€” it is updated in the container
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy # We are waiting for the database to actually start up.

  # --- 4. Worker (Ingestor) ---
  worker:
    build: .
    container_name: albion_worker
    # Run as a module so that absolute imports (from src...) work.
    command: python -m src.worker
    volumes:
      - ./src:/app/src # Hot Reload for develop
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - PYTHONUNBUFFERED=1 # To send logs directly to stdout
    depends_on:
      db:
        condition: service_healthy # Waiting for the database to be fully ready
    restart: unless-stopped